language: node_js
node_js:
  - 'stable'
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: 'renaud.genevois@hotmail.fr'
  api_key: '$NPM_TOKEN'
  before_deploy:
    - rm -rf release
  on:
    branch: release
