language: node_js
node_js:
  - 'stable'
script:
  - yarn test
  - yarn build
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  before_deploy:
    - rm -rf release
  on:
    branch: release
